yarnPath: .yarn/releases/yarn-3.6.4.cjs
nodeLinker: node-modules
packageExtensions:
    'babel-plugin-transform-flow-enums@0.0.2':
        dependencies:
            '@babel/core': '^7.0.0-0'
    'react-native@0.72.4':
        dependencies:
            '@babel/preset-env': '^7.1.6'
            '@babel/core': '^7.4.0'
